spring:
  application:
    name: SpringProject
  datasource:
    url: jdbc:mysql://localhost:3306/nobs
    username: root
    password: skadoosh
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    user:
      name: test
      password: test

server:
  error:
    include-message: always

logging:
  file:
    name: mylog.log